window.form_elements = {
	"step1": {
		"name" : "Step 1 - Input project data",
		"fill_from_template": true, // at first, all field generated by JS and inserted to the step form. But to implement custom design, JS generation was replaced by the templates.
		"fields": {
			"project_name": {
				"label": "Project name",
				"type": "text"
			},
			"product": {
				"label": "Select the product required",
				"type": "list"
			},
			"type_of_frame": {
				"label": "Type of frame",
				"type": "list"
			},
			"allowance": {
				"label": "Allowance %",
				"type": "text",
				"default_value": "5"
			},
			"product_size": {
				"label": "Product size",
				"type": "list"
			}
		},
		"template": "step1",
		"appendix": "step3_button"
	},
	"step2": {
		"name" : "Step 2 - Adding lengths",
		"fields": {},
		"template": "step2",
		"appendix": "step3_button"
	}
};

window.calculation_elements = {
	"number_of_boards": {
		"label": "No. of boards",
		"type": "text"
	},
	"number_of_fasteners": {
		"label": "No. of fasteners",
		"type": "text"
	},
	"amount_of_sealant": {
		"label": "Amount of Polyurethane sealant",
		"type": "text",
		"units" : "mL"
	}
};

window.estimation_elements = {
	"total_length_size": {
		"label": "Total length",
		"type": "text",
		"units": "m",
		"source": "db"
	},
	"fasteners_spacing": {
		"label": "Fastener spacing",
		"type": "text",
		"units": "mm",
		"source": "js",
		"value": 300
	},	
	"allowance": {
		"label": "Allowance",
		"type": "text",
		"units": "%",
		"source": "db"
	},
	"type_of_frame": {
		"label": "Type of frame",
		"type": "list",
		"units": "",
		"source": "db"
	}
};